;
; Generated by panks compiler
;

.386
.model flat, stdcall
option casemap :none

.data

A dd ?
temp_1 dd ?
temp_2 dd ?
temp_3 dd ?
temp_4 dd ?

.code
start:
    ; Объявление переменной A
push 3
push 5
pop ebx
pop eax
imul eax, ebx
mov [temp_1], eax
push temp_1
push 10
push 5
pop ebx
pop eax
cdq
idiv ebx
mov [temp_2], eax
push temp_2
push 4
pop ebx
pop eax
imul eax, ebx
mov [temp_3], eax
push temp_3
pop ebx
pop eax
add eax, ebx
mov [temp_4], eax
push temp_4
pop eax
mov [A], eax
MAIN:
push ebp
mov ebp, esp
mov esp, ebp
pop ebp
ret
    call main
    
    ; Завершение программы
    invoke ExitProcess, 0
end start
